#!/usr/bin/python -t3
import os, argparse
from subprocess import check_call

parser = argparse.ArgumentParser(description=
    "Containerized Brokertron Gateway for IB")
parser.add_argument('--trust', help="IP address for IB API to trust")
args = parser.parse_args()

if args.trust:
  check_call(["sed",
      "-e", "s|^{0}$|{0},{1}|g".format("TrustedIPs=127.0.0.1", args.trust),
      "-i", "/var/ibgateway/jts.ini"])
else:
  print("Warning: omitting --trust option is to be deprecated")
  os.system("ncat --keep-open --listen " +
                 "--sh-exec 'ncat 127.0.0.1 4001' " +
                 "0.0.0.0 4002 &")

cmdline = ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
os.execvp(cmdline[0], cmdline)

